apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: projectx-pod
spec:
  replicas: 3  #Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: projectx-pod
  template:
    metadata:
      labels:
        app: projectx-pod
    spec:
      containers:
        - name: projectx
          image: mrnithinthomas/projectx:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
